name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Ajuste conforme a versão do seu JDK
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install  # Vai procurar o pom.xml na raiz do repositório

    - name: Run tests
      run: mvn test
